export default {
  checkCode: "/api/checkCode",
  login: "/login",
  loadDataList: "/forum/loadArticle",
  avatarUrl: "/api/file/getAvatar/",
  getImage: "/api/file/getImage/",
  loadBoard: "/board/loadBoard",
  updateBoard: "/forum/updateBoard",
  auditArticle: "/forum/auditArticle",
  topArticle: "/forum/topArticle",
  delArticle: "/forum/delArticle",
  getAttachment: "/forum/getAttachment",
  loadComment4Article: "/forum/loadComment4Article",
  loadComment: "/forum/loadComment",
  delComment: "/forum/delComment",
  auditComment: "/forum/auditComment",
  loadUserList: "/user/loadUserList",
  updateUserStatus: "/user/updateUserStatus",
  sendMessage: "/user/sendMessage",
  getSetting: "/setting/getSetting",
  saveSetting: "/setting/saveSetting",
  saveBoard: "/board/saveBoard",
  delBoard: "/board/delBoard",
  changeBoardSort: "/board/changeBoardSort",
};
