export default {
  checkCode: "/api/checkCode",
  sendEmailCode: "/sendEmailCode",
  register: "/register",
  login: "/login",
  resetPwd: "/resetPwd",
  getUserInfo: "/getUserInfo",
  avatarUrl: "/api/file/getAvatar/",
  getImage: "/api/file/getImage/",
  loadBoard: "/board/loadBoard",
  loadArticle: "/forum/loadArticle",
  getArticleDetail: "/forum/getArticleDetail",
  doLike: "/forum/doLike",
  getUserDownloadInfo: "/forum/getUserDownloadInfo",
  attachmentDownload: "/api/forum/attachmentDownload",
  loadComment: "/comment/loadComment",
  postComment: "/comment/postComment",
  commentDoLike: "/comment/doLike",
  changeTopType: "/comment/changeTopType",
  loadBoard4Post: "/forum/loadBoard4Post",
  postArticle: "/forum/postArticle",
  articleDetail4Update: "/forum/articleDetail4Update",
  updateArticle: "/forum/updateArticle",
};
