export default {
  checkCode: "/api/checkCode",
  sendEmailCode: "/sendEmailCode",
  register: "/register",
  login: "/login",
  resetPwd: "/resetPwd",
  getUserInfo: "/getUserInfo",
  avatarUrl: "/api/file/getAvatar/",
  getImage: "/api/file/getImage/",
  loadBoard: "/board/loadBoard",
  loadArticle: "/forum/loadArticle",
  getArticleDetail: "/forum/getArticleDetail",
  doLike: "/forum/doLike",
  getUserDownloadInfo: "/forum/getUserDownloadInfo",
  attachmentDownload: "/api/forum/attachmentDownload",
};
